name: ai_buddy
description: AI Buddy app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  loggy: ^2.0.3
  go_router: ^11.1.3
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  flutter_chat_ui: ^1.6.12
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  file_picker: ^6.1.1
  image_picker: ^1.0.8
  syncfusion_flutter_pdf: ^24.2.4
  syncfusion_flutter_pdfviewer: ^24.2.5
  flutter_spinkit: ^5.2.0
  lottie: ^3.0.0

  # iOS
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  img: ^0.1.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
